weather:
  outputs:
    dev: 
      dbname: postgres
      host: localhost
      pass: postgres
      port: 5432
      schema: dbt_gia
      threads: 1
      type: postgres
      user: postgres
  target: dev #ยิงไปที่ dev:
